// This file was generated by jmlunit on Fri May 01 16:01:38 BST 2009.

package johnnytest;

import johnnycash.JohnnyCard;

/** Automatically-generated test driver for JML and JUnit based
 * testing of JohnnyCard. The superclass of this class should be edited
 * to supply test data. However it's best not to edit this class
 * directly; instead use the command
 * <pre>
 *  jmlunit JohnnyCard.java
 * </pre>
 * to regenerate this class whenever JohnnyCard.java changes.
 */
public class JohnnyCard_JML_Test
     extends JohnnyCard_JML_TestData
{
    /** Initialize this class. */
    public JohnnyCard_JML_Test(java.lang.String name) {
        super(name);
    }

    /** Run the tests. */
    public static void main(java.lang.String[] args) {
        org.jmlspecs.jmlunit.JMLTestRunner.run(suite());
        // You can also use a JUnit test runner such as:
        // junit.textui.TestRunner.run(suite());
    }

    /** Test to see if the code for class JohnnyCard
     * has been compiled with runtime assertion checking (i.e., by jmlc).
     * Code that is not compiled with jmlc would not make an effective test,
     * since no assertion checking would be done. */
    public void test$IsRACCompiled() {
        junit.framework.Assert.assertTrue("code for class JohnnyCard"
                + " was not compiled with jmlc"
                + " so no assertions will be checked!",
            org.jmlspecs.jmlrac.runtime.JMLChecker.isRACCompiled(JohnnyCard.class)
            );
    }

    /** Return the test suite for this test class.  This will have
    * added to it at least test$IsRACCompiled(), and any test methods
    * written explicitly by the user in the superclass.  It will also
    * have added test suites for each testing each method and
    * constructor.
    */
    //@ ensures \result != null;
    public static junit.framework.Test suite() {
        JohnnyCard_JML_Test testobj
            = new JohnnyCard_JML_Test("JohnnyCard_JML_Test");
        junit.framework.TestSuite testsuite = testobj.overallTestSuite();
        // Add instances of Test found by the reflection mechanism.
        testsuite.addTestSuite(JohnnyCard_JML_Test.class);
        testobj.addTestSuiteForEachMethod(testsuite);
        return testsuite;
    }

    /** A JUnit test object that can run a single test method.  This
     * is defined as a nested class solely for convenience; it can't
     * be defined once and for all because it must subclass its
     * enclosing class.
     */
    protected static abstract class OneTest extends JohnnyCard_JML_Test {

        /** Initialize this test object. */
        public OneTest(String name) {
            super(name);
        }

        /** The result object that holds information about testing. */
        protected junit.framework.TestResult result;

        //@ also
        //@ requires result != null;
        public void run(junit.framework.TestResult result) {
            this.result = result;
            super.run(result);
        }

        /* Run a single test and decide whether the test was
         * successful, meaningless, or a failure.  This is the
         * Template Method pattern abstraction of the inner loop in a
         * JML/JUnit test. */
        public void runTest() throws java.lang.Throwable {
            try {
                // The call being tested!
                doCall();
            }
            catch (org.jmlspecs.jmlrac.runtime.JMLEntryPreconditionError e) {
                // meaningless test input
                addMeaningless();
            } catch (org.jmlspecs.jmlrac.runtime.JMLAssertionError e) {
                // test failure
                int l = org.jmlspecs.jmlrac.runtime.JMLChecker.getLevel();
                org.jmlspecs.jmlrac.runtime.JMLChecker.setLevel
                    (org.jmlspecs.jmlrac.runtime.JMLOption.NONE);
                try {
                    java.lang.String failmsg = this.failMessage(e);
                    junit.framework.AssertionFailedError err
                        = new junit.framework.AssertionFailedError(failmsg);
                    err.setStackTrace(new java.lang.StackTraceElement[]{});
                    err.initCause(e);
                    result.addFailure(this, err);
                } finally {
                    org.jmlspecs.jmlrac.runtime.JMLChecker.setLevel(l);
                }
            } catch (java.lang.Throwable e) {
                // test success
            }
        }

        /** Call the method to be tested with the appropriate arguments. */
        protected abstract void doCall() throws java.lang.Throwable;

        /** Format the error message for a test failure, based on the
         * method's arguments. */
        protected abstract java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e);

        /** Inform listeners that a meaningless test was run. */
        private void addMeaningless() {
            if (result instanceof org.jmlspecs.jmlunit.JMLTestResult) {
                ((org.jmlspecs.jmlunit.JMLTestResult)result)
                    .addMeaningless(this);
            }
        }
    }

    /** Create the tests that are to be run for testing the class
     * JohnnyCard.  The framework will then run them.
     * @param overallTestSuite$ The suite accumulating all of the tests
     * for this driver class.
     */
    //@ requires overallTestSuite$ != null;
    public void addTestSuiteForEachMethod
        (junit.framework.TestSuite overallTestSuite$)
    {
        try {
            this.addTestSuiteFor$TestJohnnyCard(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestGetJohnnyCardId(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestSetJohnnyCardId(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestGetBalance(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestSetBalance(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestGetTransactions(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestSetTransactions(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestAddTransaction(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestAdjustBalance(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestIsLocked(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestSetLocked(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
    }

    /** Add tests for the JohnnyCard contructor
     * to the overall test suite. */
    private void addTestSuiteFor$TestJohnnyCard
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("JohnnyCard");
        try {
            methodTests$.addTest
                (new TestJohnnyCard());
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the JohnnyCard contructor. */
    protected static class TestJohnnyCard extends OneTest {

        /** Initialize this instance. */
        public TestJohnnyCard() {
            super("JohnnyCard");
        }

        protected void doCall() throws java.lang.Throwable {
            new JohnnyCard();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tContructor 'JohnnyCard'";
            return msg;
        }
    }

    /** Add tests for the getJohnnyCardId method
     * to the overall test suite. */
    private void addTestSuiteFor$TestGetJohnnyCardId
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("getJohnnyCardId");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vjohnnycash_JohnnyCardIter("getJohnnyCardId", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vjohnnycash_JohnnyCardIter(\"getJohnnyCardId\", 0))");
            while (!receivers$iter.atEnd()) {
                final johnnycash.JohnnyCard receiver$
                    = (johnnycash.JohnnyCard) receivers$iter.get();
                methodTests$.addTest
                    (new TestGetJohnnyCardId(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the getJohnnyCardId method. */
    protected static class TestGetJohnnyCardId extends OneTest {
        /** The receiver */
        private johnnycash.JohnnyCard receiver$;

        /** Initialize this instance. */
        public TestGetJohnnyCardId(johnnycash.JohnnyCard receiver$) {
            super("getJohnnyCardId");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.getJohnnyCardId();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'getJohnnyCardId' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Add tests for the setJohnnyCardId method
     * to the overall test suite. */
    private void addTestSuiteFor$TestSetJohnnyCardId
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("setJohnnyCardId");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vjohnnycash_JohnnyCardIter("setJohnnyCardId", 1));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vjohnnycash_JohnnyCardIter(\"setJohnnyCardId\", 1))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.IntIterator
                    vint$1$iter
                    = this.vintIter("setJohnnyCardId", 0);
                this.check_has_data
                    (vint$1$iter,
                     "this.vintIter(\"setJohnnyCardId\", 0)");
                while (!vint$1$iter.atEnd()) {
                    final johnnycash.JohnnyCard receiver$
                        = (johnnycash.JohnnyCard) receivers$iter.get();
                    final int theId
                        = vint$1$iter.getInt();
                    methodTests$.addTest
                        (new TestSetJohnnyCardId(receiver$, theId));
                    vint$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the setJohnnyCardId method. */
    protected static class TestSetJohnnyCardId extends OneTest {
        /** The receiver */
        private johnnycash.JohnnyCard receiver$;
        /** Argument theId */
        private int theId;

        /** Initialize this instance. */
        public TestSetJohnnyCardId(johnnycash.JohnnyCard receiver$, int theId) {
            super("setJohnnyCardId"+ ":" + theId);
            this.receiver$ = receiver$;
            this.theId = theId;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.setJohnnyCardId(theId);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'setJohnnyCardId' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument theId: " + this.theId;
            return msg;
        }
    }

    /** Add tests for the getBalance method
     * to the overall test suite. */
    private void addTestSuiteFor$TestGetBalance
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("getBalance");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vjohnnycash_JohnnyCardIter("getBalance", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vjohnnycash_JohnnyCardIter(\"getBalance\", 0))");
            while (!receivers$iter.atEnd()) {
                final johnnycash.JohnnyCard receiver$
                    = (johnnycash.JohnnyCard) receivers$iter.get();
                methodTests$.addTest
                    (new TestGetBalance(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the getBalance method. */
    protected static class TestGetBalance extends OneTest {
        /** The receiver */
        private johnnycash.JohnnyCard receiver$;

        /** Initialize this instance. */
        public TestGetBalance(johnnycash.JohnnyCard receiver$) {
            super("getBalance");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.getBalance();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'getBalance' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Add tests for the setBalance method
     * to the overall test suite. */
    private void addTestSuiteFor$TestSetBalance
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("setBalance");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vjohnnycash_JohnnyCardIter("setBalance", 1));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vjohnnycash_JohnnyCardIter(\"setBalance\", 1))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.IntIterator
                    vint$1$iter
                    = this.vintIter("setBalance", 0);
                this.check_has_data
                    (vint$1$iter,
                     "this.vintIter(\"setBalance\", 0)");
                while (!vint$1$iter.atEnd()) {
                    final johnnycash.JohnnyCard receiver$
                        = (johnnycash.JohnnyCard) receivers$iter.get();
                    final int theBalance
                        = vint$1$iter.getInt();
                    methodTests$.addTest
                        (new TestSetBalance(receiver$, theBalance));
                    vint$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the setBalance method. */
    protected static class TestSetBalance extends OneTest {
        /** The receiver */
        private johnnycash.JohnnyCard receiver$;
        /** Argument theBalance */
        private int theBalance;

        /** Initialize this instance. */
        public TestSetBalance(johnnycash.JohnnyCard receiver$, int theBalance) {
            super("setBalance"+ ":" + theBalance);
            this.receiver$ = receiver$;
            this.theBalance = theBalance;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.setBalance(theBalance);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'setBalance' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument theBalance: " + this.theBalance;
            return msg;
        }
    }

    /** Add tests for the getTransactions method
     * to the overall test suite. */
    private void addTestSuiteFor$TestGetTransactions
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("getTransactions");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vjohnnycash_JohnnyCardIter("getTransactions", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vjohnnycash_JohnnyCardIter(\"getTransactions\", 0))");
            while (!receivers$iter.atEnd()) {
                final johnnycash.JohnnyCard receiver$
                    = (johnnycash.JohnnyCard) receivers$iter.get();
                methodTests$.addTest
                    (new TestGetTransactions(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the getTransactions method. */
    protected static class TestGetTransactions extends OneTest {
        /** The receiver */
        private johnnycash.JohnnyCard receiver$;

        /** Initialize this instance. */
        public TestGetTransactions(johnnycash.JohnnyCard receiver$) {
            super("getTransactions");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.getTransactions();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'getTransactions' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Add tests for the setTransactions method
     * to the overall test suite. */
    private void addTestSuiteFor$TestSetTransactions
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("setTransactions");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vjohnnycash_JohnnyCardIter("setTransactions", 1));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vjohnnycash_JohnnyCardIter(\"setTransactions\", 1))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                    vjohnnycash_JohnnyTransaction$_$1$iter
                    = this.vjohnnycash_JohnnyTransaction$_Iter("setTransactions", 0);
                this.check_has_data
                    (vjohnnycash_JohnnyTransaction$_$1$iter,
                     "this.vjohnnycash_JohnnyTransaction$_Iter(\"setTransactions\", 0)");
                while (!vjohnnycash_JohnnyTransaction$_$1$iter.atEnd()) {
                    final johnnycash.JohnnyCard receiver$
                        = (johnnycash.JohnnyCard) receivers$iter.get();
                    final johnnycash.JohnnyTransaction[] theTransactions
                        = (johnnycash.JohnnyTransaction[]) vjohnnycash_JohnnyTransaction$_$1$iter.get();
                    methodTests$.addTest
                        (new TestSetTransactions(receiver$, theTransactions));
                    vjohnnycash_JohnnyTransaction$_$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the setTransactions method. */
    protected static class TestSetTransactions extends OneTest {
        /** The receiver */
        private johnnycash.JohnnyCard receiver$;
        /** Argument theTransactions */
        private johnnycash.JohnnyTransaction[] theTransactions;

        /** Initialize this instance. */
        public TestSetTransactions(johnnycash.JohnnyCard receiver$, johnnycash.JohnnyTransaction[] theTransactions) {
            super("setTransactions"+ ":" + (theTransactions==null?"null":("{johnnycash.JohnnyTransaction["+theTransactions.length + "]"+"}")));
            this.receiver$ = receiver$;
            this.theTransactions = theTransactions;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.setTransactions(theTransactions);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'setTransactions' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument theTransactions: " + this.theTransactions;
            return msg;
        }
    }

    /** Add tests for the addTransaction method
     * to the overall test suite. */
    private void addTestSuiteFor$TestAddTransaction
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("addTransaction");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vjohnnycash_JohnnyCardIter("addTransaction", 1));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vjohnnycash_JohnnyCardIter(\"addTransaction\", 1))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                    vjohnnycash_JohnnyTransaction$1$iter
                    = this.vjohnnycash_JohnnyTransactionIter("addTransaction", 0);
                this.check_has_data
                    (vjohnnycash_JohnnyTransaction$1$iter,
                     "this.vjohnnycash_JohnnyTransactionIter(\"addTransaction\", 0)");
                while (!vjohnnycash_JohnnyTransaction$1$iter.atEnd()) {
                    final johnnycash.JohnnyCard receiver$
                        = (johnnycash.JohnnyCard) receivers$iter.get();
                    final johnnycash.JohnnyTransaction theTransaction
                        = (johnnycash.JohnnyTransaction) vjohnnycash_JohnnyTransaction$1$iter.get();
                    methodTests$.addTest
                        (new TestAddTransaction(receiver$, theTransaction));
                    vjohnnycash_JohnnyTransaction$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the addTransaction method. */
    protected static class TestAddTransaction extends OneTest {
        /** The receiver */
        private johnnycash.JohnnyCard receiver$;
        /** Argument theTransaction */
        private johnnycash.JohnnyTransaction theTransaction;

        /** Initialize this instance. */
        public TestAddTransaction(johnnycash.JohnnyCard receiver$, johnnycash.JohnnyTransaction theTransaction) {
            super("addTransaction"+ ":" + (theTransaction==null? "null" :"{johnnycash.JohnnyTransaction}"));
            this.receiver$ = receiver$;
            this.theTransaction = theTransaction;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.addTransaction(theTransaction);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'addTransaction' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument theTransaction: " + this.theTransaction;
            return msg;
        }
    }

    /** Add tests for the adjustBalance method
     * to the overall test suite. */
    private void addTestSuiteFor$TestAdjustBalance
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("adjustBalance");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vjohnnycash_JohnnyCardIter("adjustBalance", 1));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vjohnnycash_JohnnyCardIter(\"adjustBalance\", 1))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.IntIterator
                    vint$1$iter
                    = this.vintIter("adjustBalance", 0);
                this.check_has_data
                    (vint$1$iter,
                     "this.vintIter(\"adjustBalance\", 0)");
                while (!vint$1$iter.atEnd()) {
                    final johnnycash.JohnnyCard receiver$
                        = (johnnycash.JohnnyCard) receivers$iter.get();
                    final int amount
                        = vint$1$iter.getInt();
                    methodTests$.addTest
                        (new TestAdjustBalance(receiver$, amount));
                    vint$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the adjustBalance method. */
    protected static class TestAdjustBalance extends OneTest {
        /** The receiver */
        private johnnycash.JohnnyCard receiver$;
        /** Argument amount */
        private int amount;

        /** Initialize this instance. */
        public TestAdjustBalance(johnnycash.JohnnyCard receiver$, int amount) {
            super("adjustBalance"+ ":" + amount);
            this.receiver$ = receiver$;
            this.amount = amount;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.adjustBalance(amount);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'adjustBalance' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument amount: " + this.amount;
            return msg;
        }
    }

    /** Add tests for the isLocked method
     * to the overall test suite. */
    private void addTestSuiteFor$TestIsLocked
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("isLocked");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vjohnnycash_JohnnyCardIter("isLocked", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vjohnnycash_JohnnyCardIter(\"isLocked\", 0))");
            while (!receivers$iter.atEnd()) {
                final johnnycash.JohnnyCard receiver$
                    = (johnnycash.JohnnyCard) receivers$iter.get();
                methodTests$.addTest
                    (new TestIsLocked(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the isLocked method. */
    protected static class TestIsLocked extends OneTest {
        /** The receiver */
        private johnnycash.JohnnyCard receiver$;

        /** Initialize this instance. */
        public TestIsLocked(johnnycash.JohnnyCard receiver$) {
            super("isLocked");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.isLocked();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'isLocked' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Add tests for the setLocked method
     * to the overall test suite. */
    private void addTestSuiteFor$TestSetLocked
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("setLocked");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vjohnnycash_JohnnyCardIter("setLocked", 1));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vjohnnycash_JohnnyCardIter(\"setLocked\", 1))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.BooleanIterator
                    vboolean$1$iter
                    = this.vbooleanIter("setLocked", 0);
                this.check_has_data
                    (vboolean$1$iter,
                     "this.vbooleanIter(\"setLocked\", 0)");
                while (!vboolean$1$iter.atEnd()) {
                    final johnnycash.JohnnyCard receiver$
                        = (johnnycash.JohnnyCard) receivers$iter.get();
                    final boolean theLocked
                        = vboolean$1$iter.getBoolean();
                    methodTests$.addTest
                        (new TestSetLocked(receiver$, theLocked));
                    vboolean$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the setLocked method. */
    protected static class TestSetLocked extends OneTest {
        /** The receiver */
        private johnnycash.JohnnyCard receiver$;
        /** Argument theLocked */
        private boolean theLocked;

        /** Initialize this instance. */
        public TestSetLocked(johnnycash.JohnnyCard receiver$, boolean theLocked) {
            super("setLocked"+ ":" + theLocked);
            this.receiver$ = receiver$;
            this.theLocked = theLocked;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.setLocked(theLocked);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'setLocked' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument theLocked: " + this.theLocked;
            return msg;
        }
    }

    /** Check that the iterator is non-null and not empty. */
    private void
    check_has_data(org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter,
                   String call)
    {
        if (iter == null) {
            junit.framework.Assert.fail(call + " returned null");
        }
        if (iter.atEnd()) {
            junit.framework.Assert.fail(call + " returned an empty iterator");
        }
    }

    /** Converts a char to a printable String for display */
    public static String charToString(char c) {
        if (c == '\n') {
            return "NL";
        } else if (c == '\r') {
            return "CR";
        } else if (c == '\t') {
            return "TAB";
        } else if (Character.isISOControl(c)) {
            int i = (int)c;
            return "\\u"
                    + Character.forDigit((i/2048)%16,16)
                    + Character.forDigit((i/256)%16,16)
                    + Character.forDigit((i/16)%16,16)
                    + Character.forDigit((i)%16,16);
        }
        return Character.toString(c);
    }
}
