// This file was generated by jmlunit on Thu May 07 20:07:37 BST 2009.

package niall;


/** Automatically-generated test driver for JML and JUnit based
 * testing of JohnnyRegister. The superclass of this class should be edited
 * to supply test data. However it's best not to edit this class
 * directly; instead use the command
 * <pre>
 *  jmlunit JohnnyRegister.java
 * </pre>
 * to regenerate this class whenever JohnnyRegister.java changes.
 */
public class JohnnyRegister_JML_Test
     extends JohnnyRegister_JML_TestData
{
    /** Initialize this class. */
    public JohnnyRegister_JML_Test(java.lang.String name) {
        super(name);
    }

    /** Run the tests. */
    public static void main(java.lang.String[] args) {
        org.jmlspecs.jmlunit.JMLTestRunner.run(suite());
        // You can also use a JUnit test runner such as:
        // junit.textui.TestRunner.run(suite());
    }

    /** Test to see if the code for class JohnnyRegister
     * has been compiled with runtime assertion checking (i.e., by jmlc).
     * Code that is not compiled with jmlc would not make an effective test,
     * since no assertion checking would be done. */
    public void test$IsRACCompiled() {
    	//This test does not work with the current JML compiler
        /*junit.framework.Assert.assertTrue("code for class JohnnyRegister"
                + " was not compiled with jmlc"
                + " so no assertions will be checked!",
            org.jmlspecs.jmlrac.runtime.JMLChecker.isRACCompiled(JohnnyRegister.class)
            );*/
    }

    /** Return the test suite for this test class.  This will have
    * added to it at least test$IsRACCompiled(), and any test methods
    * written explicitly by the user in the superclass.  It will also
    * have added test suites for each testing each method and
    * constructor.
    */
    //@ ensures \result != null;
    public static junit.framework.Test suite() {
        JohnnyRegister_JML_Test testobj
            = new JohnnyRegister_JML_Test("JohnnyRegister_JML_Test");
        junit.framework.TestSuite testsuite = testobj.overallTestSuite();
        // Add instances of Test found by the reflection mechanism.
        testsuite.addTestSuite(JohnnyRegister_JML_Test.class);
        testobj.addTestSuiteForEachMethod(testsuite);
        return testsuite;
    }

    /** A JUnit test object that can run a single test method.  This
     * is defined as a nested class solely for convenience; it can't
     * be defined once and for all because it must subclass its
     * enclosing class.
     */
    protected static abstract class OneTest extends JohnnyRegister_JML_Test {

        /** Initialize this test object. */
        public OneTest(String name) {
            super(name);
        }

        /** The result object that holds information about testing. */
        protected junit.framework.TestResult result;

        //@ also
        //@ requires result != null;
        public void run(junit.framework.TestResult result) {
            this.result = result;
            super.run(result);
        }

        /* Run a single test and decide whether the test was
         * successful, meaningless, or a failure.  This is the
         * Template Method pattern abstraction of the inner loop in a
         * JML/JUnit test. */
        public void runTest() throws java.lang.Throwable {
            try {
                // The call being tested!
                doCall();
            }
            catch (org.jmlspecs.jmlrac.runtime.JMLEntryPreconditionError e) {
                // meaningless test input
                addMeaningless();
            } catch (org.jmlspecs.jmlrac.runtime.JMLAssertionError e) {
                // test failure
                int l = org.jmlspecs.jmlrac.runtime.JMLChecker.getLevel();
                org.jmlspecs.jmlrac.runtime.JMLChecker.setLevel
                    (org.jmlspecs.jmlrac.runtime.JMLOption.NONE);
                try {
                    java.lang.String failmsg = this.failMessage(e);
                    junit.framework.AssertionFailedError err
                        = new junit.framework.AssertionFailedError(failmsg);
                    err.setStackTrace(new java.lang.StackTraceElement[]{});
                    err.initCause(e);
                    result.addFailure(this, err);
                } finally {
                    org.jmlspecs.jmlrac.runtime.JMLChecker.setLevel(l);
                }
            } catch (java.lang.Throwable e) {
                // test success
            }
        }

        /** Call the method to be tested with the appropriate arguments. */
        protected abstract void doCall() throws java.lang.Throwable;

        /** Format the error message for a test failure, based on the
         * method's arguments. */
        protected abstract java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e);

        /** Inform listeners that a meaningless test was run. */
        private void addMeaningless() {
            if (result instanceof org.jmlspecs.jmlunit.JMLTestResult) {
                ((org.jmlspecs.jmlunit.JMLTestResult)result)
                    .addMeaningless(this);
            }
        }
    }

    /** Create the tests that are to be run for testing the class
     * JohnnyRegister.  The framework will then run them.
     * @param overallTestSuite$ The suite accumulating all of the tests
     * for this driver class.
     */
    //@ requires overallTestSuite$ != null;
    public void addTestSuiteForEachMethod
        (junit.framework.TestSuite overallTestSuite$)
    {
        try {
            this.addTestSuiteFor$TestJohnnyRegister(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestGetTransactions(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestRecordTransaction(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
    }

    /** Add tests for the JohnnyRegister contructor
     * to the overall test suite. */
    private void addTestSuiteFor$TestJohnnyRegister
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("JohnnyRegister");
        try {
            methodTests$.addTest
                (new TestJohnnyRegister());
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the JohnnyRegister contructor. */
    protected static class TestJohnnyRegister extends OneTest {

        /** Initialize this instance. */
        public TestJohnnyRegister() {
            super("JohnnyRegister");
        }

        protected void doCall() throws java.lang.Throwable {
            new JohnnyRegister();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tContructor 'JohnnyRegister'";
            return msg;
        }
    }

    /** Add tests for the getTransactions method
     * to the overall test suite. */
    private void addTestSuiteFor$TestGetTransactions
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("getTransactions");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vniall_JohnnyRegisterIter("getTransactions", 0));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vniall_JohnnyRegisterIter(\"getTransactions\", 0))");
            while (!receivers$iter.atEnd()) {
                final niall.JohnnyRegister receiver$
                    = (niall.JohnnyRegister) receivers$iter.get();
                methodTests$.addTest
                    (new TestGetTransactions(receiver$));
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the getTransactions method. */
    protected static class TestGetTransactions extends OneTest {
        /** The receiver */
        private niall.JohnnyRegister receiver$;

        /** Initialize this instance. */
        public TestGetTransactions(niall.JohnnyRegister receiver$) {
            super("getTransactions");
            this.receiver$ = receiver$;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.getTransactions();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'getTransactions' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            return msg;
        }
    }

    /** Add tests for the recordTransaction method
     * to the overall test suite. */
    private void addTestSuiteFor$TestRecordTransaction
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("recordTransaction");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vniall_JohnnyRegisterIter("recordTransaction", 3));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vniall_JohnnyRegisterIter(\"recordTransaction\", 3))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                    vniall_JohnnyCard$1$iter
                    = this.vniall_JohnnyCardIter("recordTransaction", 2);
                this.check_has_data
                    (vniall_JohnnyCard$1$iter,
                     "this.vniall_JohnnyCardIter(\"recordTransaction\", 2)");
                while (!vniall_JohnnyCard$1$iter.atEnd()) {
                    org.jmlspecs.jmlunit.strategies.IntIterator
                        vint$2$iter
                        = this.vintIter("recordTransaction", 1);
                    this.check_has_data
                        (vint$2$iter,
                         "this.vintIter(\"recordTransaction\", 1)");
                    while (!vint$2$iter.atEnd()) {
                        org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                            vjava_util_Date$3$iter
                            = this.vjava_util_DateIter("recordTransaction", 0);
                        this.check_has_data
                            (vjava_util_Date$3$iter,
                             "this.vjava_util_DateIter(\"recordTransaction\", 0)");
                        while (!vjava_util_Date$3$iter.atEnd()) {
                            final niall.JohnnyRegister receiver$
                                = (niall.JohnnyRegister) receivers$iter.get();
                            final niall.JohnnyCard card
                                = (niall.JohnnyCard) vniall_JohnnyCard$1$iter.get();
                            final int amount
                                = vint$2$iter.getInt();
                            final java.util.Date date
                                = (java.util.Date) vjava_util_Date$3$iter.get();
                            methodTests$.addTest
                                (new TestRecordTransaction(receiver$, card, amount, date));
                            vjava_util_Date$3$iter.advance();
                        }
                        vint$2$iter.advance();
                    }
                    vniall_JohnnyCard$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the recordTransaction method. */
    protected static class TestRecordTransaction extends OneTest {
        /** The receiver */
        private niall.JohnnyRegister receiver$;
        /** Argument card */
        private niall.JohnnyCard card;
        /** Argument amount */
        private int amount;
        /** Argument date */
        private java.util.Date date;

        /** Initialize this instance. */
        public TestRecordTransaction(niall.JohnnyRegister receiver$, niall.JohnnyCard card, int amount, java.util.Date date) {
            super("recordTransaction"+ ":" + (card==null? "null" :"{niall.JohnnyCard}")+ "," +amount+ "," +(date==null? "null" :"{java.util.Date}"));
            this.receiver$ = receiver$;
            this.card = card;
            this.amount = amount;
            this.date = date;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.recordTransaction(card, amount, date);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'recordTransaction' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument card: " + this.card;
            msg += "\n\tArgument amount: " + this.amount;
            msg += "\n\tArgument date: " + this.date;
            return msg;
        }
    }

    /** Check that the iterator is non-null and not empty. */
    private void
    check_has_data(org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter,
                   String call)
    {
        if (iter == null) {
            junit.framework.Assert.fail(call + " returned null");
        }
        if (iter.atEnd()) {
            junit.framework.Assert.fail(call + " returned an empty iterator");
        }
    }

    /** Converts a char to a printable String for display */
    public static String charToString(char c) {
        if (c == '\n') {
            return "NL";
        } else if (c == '\r') {
            return "CR";
        } else if (c == '\t') {
            return "TAB";
        } else if (Character.isISOControl(c)) {
            int i = (int)c;
            return "\\u"
                    + Character.forDigit((i/2048)%16,16)
                    + Character.forDigit((i/256)%16,16)
                    + Character.forDigit((i/16)%16,16)
                    + Character.forDigit((i)%16,16);
        }
        return Character.toString(c);
    }
}
