
#ifndef __INTERPRETER_SHAPEID_H__
#define __INTERPRETER_SHAPEID_H__

namespace interpreter
{

/**
 * List of all shapes by their id in the kinephon.sec shape file
 * This header was generated by Shed
 * @author EB
 * @version 1.0
 */
namespace esid
{

	sid const TRIANGLE  = 1; // Movement
	sid const TRI_SOFT  = 2; // - Speed
	sid const TRI_SHARP = 3; // - Speed
	sid const TRI_SLOW  = 4; // - Accel
	
	//commmads for audio
	sid const DYNAMICS_PIANO = 0;//for soft music dynamics
	sid const DYNAMICS_FORTE = 0;//for loud music dynamics
	sid const DYNAMICS_PIANISSIMO = 0;//for very quiet music dynamics
	sid const DYNAMICS_FORTISSIMO = 0;//for very loud music dynamics
	sid const RHYTHM_1_4 = 0;//for rythm music
	sid const RHYTHM_2_4 = 0;
	sid const RHYTHM_3_4 = 0;
	sid const RHYTHM_4_4 = 0;
	sid const RHYTHM_1_2 = 0;
	sid const RHYTHM_2_3 = 0;
	sid const RHYTHM_NONE  = 0;
	sid const CHORDS_FIRST = 0;
	sid const CHORDS_SECOND = 0;
	sid const CHORDS_THIRD = 0;
	sid const CHORDS_ONEOFF = 0;
	sid const CHORDS_NONE  = 0;
	sid const INSTRUMENT_CLASSIC = 0;
	sid const INSTRUMENT_CRAZY = 0;
	sid const INSTRUMENT_WIND = 0;
}

}

#endif
