#ifndef __INTERPRETER_SHAPE_H__
#define __INTERPRETER_SHAPE_H__

namespace interpreter
{

/**
 * List of all shapes by their id in the kinephon.sec shape file
 * This header was generated by Shed
 * @author EB
 * @version 1.0
 */
namespace esid
{

	sid const TRIANGLE  = 1; // Movement
	sid const TRI_SOFT  = 2; // - Speed
	sid const TRI_SHARP = 3; // - Speed
	sid const TRI_SLOW  = 4; // - Accel

}

}

#endif
