// This file was generated by jmlunit on Sun May 10 22:14:55 BST 2009.

package tests;

import cashsystem.*;

/** Automatically-generated test driver for JML and JUnit based
 * testing of JohnnyBank. The superclass of this class should be edited
 * to supply test data. However it's best not to edit this class
 * directly; instead use the command
 * <pre>
 *  jmlunit JohnnyBank.java
 * </pre>
 * to regenerate this class whenever JohnnyBank.java changes.
 */
public class JohnnyBank_JML_Test
     extends JohnnyBank_JML_TestData
{
    /** Initialize this class. */
    public JohnnyBank_JML_Test(java.lang.String name) {
        super(name);
    }

    /** Run the tests. */
    public static void main(java.lang.String[] args) {
        org.jmlspecs.jmlunit.JMLTestRunner.run(suite());
        // You can also use a JUnit test runner such as:
        // junit.textui.TestRunner.run(suite());
    }

    /** Test to see if the code for class JohnnyBank
     * has been compiled with runtime assertion checking (i.e., by jmlc).
     * Code that is not compiled with jmlc would not make an effective test,
     * since no assertion checking would be done. */
    public void test$IsRACCompiled() {
        junit.framework.Assert.assertTrue("code for class JohnnyBank"
                + " was not compiled with jmlc"
                + " so no assertions will be checked!",
            org.jmlspecs.jmlrac.runtime.JMLChecker.isRACCompiled(JohnnyBank.class)
            );
    }

    /** Return the test suite for this test class.  This will have
    * added to it at least test$IsRACCompiled(), and any test methods
    * written explicitly by the user in the superclass.  It will also
    * have added test suites for each testing each method and
    * constructor.
    */
    //@ ensures \result != null;
    public static junit.framework.Test suite() {
        JohnnyBank_JML_Test testobj
            = new JohnnyBank_JML_Test("JohnnyBank_JML_Test");
        junit.framework.TestSuite testsuite = testobj.overallTestSuite();
        // Add instances of Test found by the reflection mechanism.
        testsuite.addTestSuite(JohnnyBank_JML_Test.class);
        testobj.addTestSuiteForEachMethod(testsuite);
        return testsuite;
    }

    /** A JUnit test object that can run a single test method.  This
     * is defined as a nested class solely for convenience; it can't
     * be defined once and for all because it must subclass its
     * enclosing class.
     */
    protected static abstract class OneTest extends JohnnyBank_JML_Test {

        /** Initialize this test object. */
        public OneTest(String name) {
            super(name);
        }

        /** The result object that holds information about testing. */
        protected junit.framework.TestResult result;

        //@ also
        //@ requires result != null;
        public void run(junit.framework.TestResult result) {
            this.result = result;
            super.run(result);
        }

        /* Run a single test and decide whether the test was
         * successful, meaningless, or a failure.  This is the
         * Template Method pattern abstraction of the inner loop in a
         * JML/JUnit test. */
        public void runTest() throws java.lang.Throwable {
            try {
                // The call being tested!
                doCall();
            }
            catch (org.jmlspecs.jmlrac.runtime.JMLEntryPreconditionError e) {
                // meaningless test input
                addMeaningless();
            } catch (org.jmlspecs.jmlrac.runtime.JMLAssertionError e) {
                // test failure
                int l = org.jmlspecs.jmlrac.runtime.JMLChecker.getLevel();
                org.jmlspecs.jmlrac.runtime.JMLChecker.setLevel
                    (org.jmlspecs.jmlrac.runtime.JMLOption.NONE);
                try {
                    java.lang.String failmsg = this.failMessage(e);
                    junit.framework.AssertionFailedError err
                        = new junit.framework.AssertionFailedError(failmsg);
                    err.setStackTrace(new java.lang.StackTraceElement[]{});
                    err.initCause(e);
                    result.addFailure(this, err);
                } finally {
                    org.jmlspecs.jmlrac.runtime.JMLChecker.setLevel(l);
                }
            } catch (java.lang.Throwable e) {
                // test success
            }
        }

        /** Call the method to be tested with the appropriate arguments. */
        protected abstract void doCall() throws java.lang.Throwable;

        /** Format the error message for a test failure, based on the
         * method's arguments. */
        protected abstract java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e);

        /** Inform listeners that a meaningless test was run. */
        private void addMeaningless() {
            if (result instanceof org.jmlspecs.jmlunit.JMLTestResult) {
                ((org.jmlspecs.jmlunit.JMLTestResult)result)
                    .addMeaningless(this);
            }
        }
    }

    /** Create the tests that are to be run for testing the class
     * JohnnyBank.  The framework will then run them.
     * @param overallTestSuite$ The suite accumulating all of the tests
     * for this driver class.
     */
    //@ requires overallTestSuite$ != null;
    public void addTestSuiteForEachMethod
        (junit.framework.TestSuite overallTestSuite$)
    {
        try {
            this.addTestSuiteFor$TestJohnnyBank(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestGetBankBalance(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestWithdraw(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestLodge(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
        try {
            this.addTestSuiteFor$TestIsBankAccountValid(overallTestSuite$);
        } catch (java.lang.Throwable ex) {
            overallTestSuite$.addTest
                (new org.jmlspecs.jmlunit.strategies.ConstructorFailed(ex));
        }
    }

    /** Add tests for the JohnnyBank contructor
     * to the overall test suite. */
    private void addTestSuiteFor$TestJohnnyBank
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("JohnnyBank");
        try {
            methodTests$.addTest
                (new TestJohnnyBank());
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the JohnnyBank contructor. */
    protected static class TestJohnnyBank extends OneTest {

        /** Initialize this instance. */
        public TestJohnnyBank() {
            super("JohnnyBank");
        }

        protected void doCall() throws java.lang.Throwable {
            new JohnnyBank();
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tContructor 'JohnnyBank'";
            return msg;
        }
    }

    /** Add tests for the getBankBalance method
     * to the overall test suite. */
    private void addTestSuiteFor$TestGetBankBalance
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("getBankBalance");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vcashsystem_JohnnyBankIter("getBankBalance", 1));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vcashsystem_JohnnyBankIter(\"getBankBalance\", 1))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.IntIterator
                    vint$1$iter
                    = this.vintIter("getBankBalance", 0);
                this.check_has_data
                    (vint$1$iter,
                     "this.vintIter(\"getBankBalance\", 0)");
                while (!vint$1$iter.atEnd()) {
                    final cashsystem.JohnnyBank receiver$
                        = (cashsystem.JohnnyBank) receivers$iter.get();
                    final int acct_id
                        = vint$1$iter.getInt();
                    methodTests$.addTest
                        (new TestGetBankBalance(receiver$, acct_id));
                    vint$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the getBankBalance method. */
    protected static class TestGetBankBalance extends OneTest {
        /** The receiver */
        private cashsystem.JohnnyBank receiver$;
        /** Argument acct_id */
        private int acct_id;

        /** Initialize this instance. */
        public TestGetBankBalance(cashsystem.JohnnyBank receiver$, int acct_id) {
            super("getBankBalance"+ ":" + acct_id);
            this.receiver$ = receiver$;
            this.acct_id = acct_id;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.getBankBalance(acct_id);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'getBankBalance' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument acct_id: " + this.acct_id;
            return msg;
        }
    }

    /** Add tests for the withdraw method
     * to the overall test suite. */
    private void addTestSuiteFor$TestWithdraw
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("withdraw");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vcashsystem_JohnnyBankIter("withdraw", 2));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vcashsystem_JohnnyBankIter(\"withdraw\", 2))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.IntIterator
                    vint$1$iter
                    = this.vintIter("withdraw", 1);
                this.check_has_data
                    (vint$1$iter,
                     "this.vintIter(\"withdraw\", 1)");
                while (!vint$1$iter.atEnd()) {
                    org.jmlspecs.jmlunit.strategies.IntIterator
                        vint$2$iter
                        = this.vintIter("withdraw", 0);
                    this.check_has_data
                        (vint$2$iter,
                         "this.vintIter(\"withdraw\", 0)");
                    while (!vint$2$iter.atEnd()) {
                        final cashsystem.JohnnyBank receiver$
                            = (cashsystem.JohnnyBank) receivers$iter.get();
                        final int acct_id
                            = vint$1$iter.getInt();
                        final int amount
                            = vint$2$iter.getInt();
                        methodTests$.addTest
                            (new TestWithdraw(receiver$, acct_id, amount));
                        vint$2$iter.advance();
                    }
                    vint$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the withdraw method. */
    protected static class TestWithdraw extends OneTest {
        /** The receiver */
        private cashsystem.JohnnyBank receiver$;
        /** Argument acct_id */
        private int acct_id;
        /** Argument amount */
        private int amount;

        /** Initialize this instance. */
        public TestWithdraw(cashsystem.JohnnyBank receiver$, int acct_id, int amount) {
            super("withdraw"+ ":" + acct_id+ "," +amount);
            this.receiver$ = receiver$;
            this.acct_id = acct_id;
            this.amount = amount;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.withdraw(acct_id, amount);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'withdraw' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument acct_id: " + this.acct_id;
            msg += "\n\tArgument amount: " + this.amount;
            return msg;
        }
    }

    /** Add tests for the lodge method
     * to the overall test suite. */
    private void addTestSuiteFor$TestLodge
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("lodge");
        try {
            org.jmlspecs.jmlunit.strategies.IndefiniteIterator
                receivers$iter
                = new org.jmlspecs.jmlunit.strategies.NonNullIteratorDecorator
                    (this.vcashsystem_JohnnyBankIter("lodge", 2));
            this.check_has_data
                (receivers$iter,
                 "new NonNullIteratorDecorator(this.vcashsystem_JohnnyBankIter(\"lodge\", 2))");
            while (!receivers$iter.atEnd()) {
                org.jmlspecs.jmlunit.strategies.IntIterator
                    vint$1$iter
                    = this.vintIter("lodge", 1);
                this.check_has_data
                    (vint$1$iter,
                     "this.vintIter(\"lodge\", 1)");
                while (!vint$1$iter.atEnd()) {
                    org.jmlspecs.jmlunit.strategies.IntIterator
                        vint$2$iter
                        = this.vintIter("lodge", 0);
                    this.check_has_data
                        (vint$2$iter,
                         "this.vintIter(\"lodge\", 0)");
                    while (!vint$2$iter.atEnd()) {
                        final cashsystem.JohnnyBank receiver$
                            = (cashsystem.JohnnyBank) receivers$iter.get();
                        final int acct_id
                            = vint$1$iter.getInt();
                        final int amount
                            = vint$2$iter.getInt();
                        methodTests$.addTest
                            (new TestLodge(receiver$, acct_id, amount));
                        vint$2$iter.advance();
                    }
                    vint$1$iter.advance();
                }
                receivers$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the lodge method. */
    protected static class TestLodge extends OneTest {
        /** The receiver */
        private cashsystem.JohnnyBank receiver$;
        /** Argument acct_id */
        private int acct_id;
        /** Argument amount */
        private int amount;

        /** Initialize this instance. */
        public TestLodge(cashsystem.JohnnyBank receiver$, int acct_id, int amount) {
            super("lodge"+ ":" + acct_id+ "," +amount);
            this.receiver$ = receiver$;
            this.acct_id = acct_id;
            this.amount = amount;
        }

        protected void doCall() throws java.lang.Throwable {
            receiver$.lodge(acct_id, amount);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'lodge' applied to";
            msg += "\n\tReceiver: " + this.receiver$;
            msg += "\n\tArgument acct_id: " + this.acct_id;
            msg += "\n\tArgument amount: " + this.amount;
            return msg;
        }
    }

    /** Add tests for the isBankAccountValid method
     * to the overall test suite. */
    private void addTestSuiteFor$TestIsBankAccountValid
        (junit.framework.TestSuite overallTestSuite$)
    {
        junit.framework.TestSuite methodTests$
            = this.emptyTestSuiteFor("isBankAccountValid");
        try {
            org.jmlspecs.jmlunit.strategies.IntIterator
                vint$1$iter
                = this.vintIter("isBankAccountValid", 0);
            this.check_has_data
                (vint$1$iter,
                 "this.vintIter(\"isBankAccountValid\", 0)");
            while (!vint$1$iter.atEnd()) {
                final int number
                    = vint$1$iter.getInt();
                methodTests$.addTest
                    (new TestIsBankAccountValid(number));
                vint$1$iter.advance();
            }
        } catch (org.jmlspecs.jmlunit.strategies.TestSuiteFullException e$) {
            // methodTests$ doesn't want more tests
        }
        overallTestSuite$.addTest(methodTests$);
    }

    /** Test for the isBankAccountValid method. */
    protected static class TestIsBankAccountValid extends OneTest {
        /** Argument number */
        private int number;

        /** Initialize this instance. */
        public TestIsBankAccountValid(int number) {
            super("isBankAccountValid"+ ":" + number);
            this.number = number;
        }

        protected void doCall() throws java.lang.Throwable {
            JohnnyBank.isBankAccountValid(number);
        }

        protected java.lang.String failMessage
            (org.jmlspecs.jmlrac.runtime.JMLAssertionError e$)
        {
            java.lang.String msg = "\n\tMethod 'isBankAccountValid' applied to";
            msg += "\n\tReceiver class JohnnyBank";
            msg += "\n\tArgument number: " + this.number;
            return msg;
        }
    }

    /** Check that the iterator is non-null and not empty. */
    private void
    check_has_data(org.jmlspecs.jmlunit.strategies.IndefiniteIterator iter,
                   String call)
    {
        if (iter == null) {
            junit.framework.Assert.fail(call + " returned null");
        }
        if (iter.atEnd()) {
            junit.framework.Assert.fail(call + " returned an empty iterator");
        }
    }

    /** Converts a char to a printable String for display */
    public static String charToString(char c) {
        if (c == '\n') {
            return "NL";
        } else if (c == '\r') {
            return "CR";
        } else if (c == '\t') {
            return "TAB";
        } else if (Character.isISOControl(c)) {
            int i = (int)c;
            return "\\u"
                    + Character.forDigit((i/2048)%16,16)
                    + Character.forDigit((i/256)%16,16)
                    + Character.forDigit((i/16)%16,16)
                    + Character.forDigit((i)%16,16);
        }
        return Character.toString(c);
    }
}
